/** Kid-facing control labels: symbols first (Seth is 5 and may not read Chinese). */
export const KID = {
  back: '←',
  prev: '←',
  next: '→',
  doneHome: '★ →',
  doneToday: '★',
  listen: '▶',
  listenAll: '▶▶',
  listenEn: '▶ EN',
  check: '✓',
  peek: '?',
  help: '?',
  starOk: '★',
  readDone: '★ 讀完啦',
  speakDone: '★ 講完啦',
  mic: '●',
  micStop: '■',
  micLabel: '●',
  cantonese: '粵',
  english: 'EN',
  parentHint: 'P',
  soundOn: '♪',
  soundOff: '×♪',
} as const
